-- MySQL Script generated by MySQL Workbench
-- Fri Mar  3 21:54:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb`;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Kayttaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kayttaja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nimi` VARCHAR(15) NOT NULL,
  `sahkoposti` VARCHAR(50) NOT NULL,
  `salasana` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sahkoposti_UNIQUE` (`sahkoposti` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aurinkopaneeli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aurinkopaneeli` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `malli` VARCHAR(40) NOT NULL,
  `valmistaja` VARCHAR(30) NOT NULL,
  `tehokkuus` DECIMAL(4,2) NOT NULL,
  `hinta` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asentaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asentaja` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nimi` VARCHAR(50) NOT NULL,
  `sahkoposti` VARCHAR(50) NOT NULL,
  `puhelinnumero` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Asennus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Asennus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paivamaara` DATE NOT NULL,
  `paneelien_maara` INT NOT NULL CHECK (paneelien_maara > 0),
  `paikkakunta` VARCHAR(20) NOT NULL,
  `kesto_tunteina` INT NOT NULL,
  `asennuksen_hinta` DECIMAL(10,2) NOT NULL,
  `Asentaja_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Asentaja_id`),
  INDEX `fk_Asennus_Asentaja1_idx` (`Asentaja_id` ASC) VISIBLE,
  CONSTRAINT `fk_Asennus_Asentaja1`
    FOREIGN KEY (`Asentaja_id`)
    REFERENCES `mydb`.`Asentaja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarvikkeet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarvikkeet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kaytetyt_tarvikkeet` TINYTEXT NOT NULL ,
  `tarvikkeiden_kokonaishinta` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Huolto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Huolto` (
  `huoltonumero` INT NULL,
  `huoltaja` VARCHAR(50) NULL DEFAULT 'Tuntematon',
  `toimenpiteet` TINYTEXT NULL,
  `paivamaara` DATE NULL,
  `huollon_hinta` DECIMAL(5,2) NULL,
  `Aurinkopaneeli_id` INT NULL,
  INDEX `fk_Huolto_Aurinkopaneeli1_idx` (`Aurinkopaneeli_id` ASC) VISIBLE,
  CONSTRAINT `fk_Huolto_Aurinkopaneeli1`
    FOREIGN KEY (`Aurinkopaneeli_id`)
    REFERENCES `mydb`.`Aurinkopaneeli` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kokonaiskustannukset`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kokonaiskustannukset` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `kustannukset_yhteensa` DECIMAL(6,2) NOT NULL,
  `Aurinkopaneeli_id` INT NOT NULL,
  `Asennus_id` INT NOT NULL,
  `Asennus_Asentaja_id` INT NOT NULL,
  `Tarvikkeet_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Aurinkopaneeli_id`, `Asennus_id`, `Asennus_Asentaja_id`, `Tarvikkeet_id`),
  INDEX `fk_Kokonaiskustannukset_Aurinkopaneeli1_idx` (`Aurinkopaneeli_id` ASC) VISIBLE,
  INDEX `fk_Kokonaiskustannukset_Asennus1_idx` (`Asennus_id` ASC, `Asennus_Asentaja_id` ASC) VISIBLE,
  INDEX `fk_Kokonaiskustannukset_Tarvikkeet1_idx` (`Tarvikkeet_id` ASC) VISIBLE,
  CONSTRAINT `fk_Kokonaiskustannukset_Aurinkopaneeli1`
    FOREIGN KEY (`Aurinkopaneeli_id`)
    REFERENCES `mydb`.`Aurinkopaneeli` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kokonaiskustannukset_Asennus1`
    FOREIGN KEY (`Asennus_id` , `Asennus_Asentaja_id`)
    REFERENCES `mydb`.`Asennus` (`id` , `Asentaja_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kokonaiskustannukset_Tarvikkeet1`
    FOREIGN KEY (`Tarvikkeet_id`)
    REFERENCES `mydb`.`Tarvikkeet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kayttaja_has_Aurinkopaneeli`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kayttaja_has_Aurinkopaneeli` (
  `Kayttaja_id` INT NOT NULL,
  `Aurinkopaneeli_id` INT NOT NULL,
  PRIMARY KEY (`Kayttaja_id`, `Aurinkopaneeli_id`),
  INDEX `fk_Kayttaja_has_Aurinkopaneeli_Aurinkopaneeli1_idx` (`Aurinkopaneeli_id` ASC) VISIBLE,
  INDEX `fk_Kayttaja_has_Aurinkopaneeli_Kayttaja1_idx` (`Kayttaja_id` ASC) VISIBLE,
  CONSTRAINT `fk_Kayttaja_has_Aurinkopaneeli_Kayttaja1`
    FOREIGN KEY (`Kayttaja_id`)
    REFERENCES `mydb`.`Kayttaja` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Kayttaja_has_Aurinkopaneeli_Aurinkopaneeli1`
    FOREIGN KEY (`Aurinkopaneeli_id`)
    REFERENCES `mydb`.`Aurinkopaneeli` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aurinkopaneeli_has_Asennus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aurinkopaneeli_has_Asennus` (
  `Aurinkopaneeli_id` INT NOT NULL,
  `Asennus_id` INT NOT NULL,
  `Asennus_Asentaja_id` INT NOT NULL,
  PRIMARY KEY (`Aurinkopaneeli_id`, `Asennus_id`, `Asennus_Asentaja_id`),
  INDEX `fk_Aurinkopaneeli_has_Asennus_Asennus1_idx` (`Asennus_id` ASC, `Asennus_Asentaja_id` ASC) VISIBLE,
  INDEX `fk_Aurinkopaneeli_has_Asennus_Aurinkopaneeli1_idx` (`Aurinkopaneeli_id` ASC) VISIBLE,
  CONSTRAINT `fk_Aurinkopaneeli_has_Asennus_Aurinkopaneeli1`
    FOREIGN KEY (`Aurinkopaneeli_id`)
    REFERENCES `mydb`.`Aurinkopaneeli` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aurinkopaneeli_has_Asennus_Asennus1`
    FOREIGN KEY (`Asennus_id` , `Asennus_Asentaja_id`)
    REFERENCES `mydb`.`Asennus` (`id` , `Asentaja_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Näkymien luonti 
-- -----------------------------------------------------

CREATE VIEW aurinkopaneeli_asennus_view AS
SELECT a.malli, a.valmistaja, a.tehokkuus, k.Kayttaja_id, k.Aurinkopaneeli_id, s.paivamaara, s.paneelien_maara, s.paikkakunta, s.kesto_tunteina, s.asennuksen_hinta, s.Asentaja_id
FROM Aurinkopaneeli a
INNER JOIN Kayttaja_has_Aurinkopaneeli k ON a.id = k.Aurinkopaneeli_id
INNER JOIN Asennus s ON s.Asentaja_id = k.Kayttaja_id;


CREATE VIEW paikkakunta_hinta_view AS
SELECT paikkakunta, COUNT(*) AS num_asennukset, AVG(asennuksen_hinta) AS avg_hinta
FROM Asennus
GROUP BY paikkakunta;

-- -----------------------------------------------------
-- datarivien lisäys tauluihin
-- -----------------------------------------------------

INSERT INTO `mydb`.`Kayttaja` (`nimi`, `sahkoposti`, `salasana`) VALUES
('Matti', 'matti@yahoo.com', 'aurinko10'),
('Teppo', 'teppo1@gmail.com', 'joopajoo123'),
('Seppo', 'seppo.s@gmail.com', 'salasana'),
('Jaana', 'jaana111@outlook.com', 'koira11'),
('Joonas', 'joon45@gmail.com', 'salis33'),
('Sari', 'sari_123@gmail.com', 'salasana123'),
('Mikko', 'mikko_m@gmail.com', 'mikko1234'),
('Emma', 'emma99@gmail.com', 'emmaemma'),
('Timo', 'timo_t@gmail.com', 'timotimo'),
('Anna', 'anna12@gmail.com', 'salasana123');


INSERT INTO `mydb`.`aurinkopaneeli` (`malli`, `valmistaja`, `tehokkuus`, `hinta`) VALUES 
('Malli 1', 'Valmistaja 1', 15.5, 200),
('Malli 2', 'Valmistaja 2', 17.0, 250),
('Malli 3', 'Valmistaja 3', 19.2, 300),
('Malli 4', 'Valmistaja 4', 20.0, 350),
('Malli 5', 'Valmistaja 5', 21.5, 400),
('Malli 6', 'Valmistaja 6', 18.0, 275),
('Malli 7', 'Valmistaja 7', 16.8, 225),
('Malli 8', 'Valmistaja 8', 19.5, 310),
('Malli 9', 'Valmistaja 9', 22.0, 450),
('Malli 10', 'Valmistaja 10', 20.5, 375);

INSERT INTO `mydb`.`kayttaja_has_aurinkopaneeli` (`kayttaja_id`, `aurinkopaneeli_id`) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10);


INSERT INTO `mydb`.`Asentaja` (`nimi`, `sahkoposti`, `puhelinnumero`) VALUES 
('Arto', 'arto@asentaja.fi', '0409788759'),
('Antti', 'antti1@gmail.com', '0502234544'),
('Jussi', 'jussij@asennukset.com', '0401928383'),
('Anni', 'annip00@outlook.com', '0505667937'),
('Mikko', 'mikko_a@gmail.com', '0401234567'),
('Anna', 'anna11@gmail.com', '0507654321'),
('Janne', 'janne22@gmail.com', '0401122334'),
('Marja', 'marja.m@gmail.com', '0509988776'),
('Timo', 'timo_t1@gmail.com', '0404433221'),
('Kati', 'kati_k@gmail.com', '0501122334');


INSERT INTO `mydb`.`Asennus` (`paivamaara`, `paneelien_maara`, `paikkakunta`, `kesto_tunteina`, `asennuksen_hinta`, `Asentaja_id`) VALUES
('2022-02-20', 10, 'Helsinki', 8, 1500.00, 1),
('2022-01-22', 8, 'Turku', 6, 1200.00, 2),
('2022-01-11', 6, 'Tampere', 4, 1000.00, 3),
('2021-12-3', 12, 'Oulu', 10, 2000.00, 4),
('2022-05-01', 9, 'Espoo', 7, 1300.00, 5),
('2022-04-15', 7, 'Rovaniemi', 5, 900.00, 6),
('2022-03-20', 11, 'Kouvola', 9, 1700.00, 7),
('2022-02-18', 13, 'Seinäjoki', 11, 2100.00, 8),
('2022-01-10', 4, 'Mikkeli', 3, 600.00, 9),
('2021-12-05', 16, 'Kokkola', 14, 2600.00, 10);


INSERT INTO `mydb`.`Huolto` (`Aurinkopaneeli_id`, `huoltaja`, `toimenpiteet`, `paivamaara`, `huollon_hinta`) VALUES
(1, 'Matti', 'Korjasi kaapelin', '2022-02-02', 50.00),
(2, 'Jouni', 'Puhdisti paneelin', '2022-01-05', 70.00),
(3, 'Liisa', 'Tarkasti invertterin', '2021-12-12', 100.00),
(4, 'Maija', 'Vaihtoi aurinkopaneelin', '2022-03-03', 200.00),
(5, 'Pekka', 'Korjasi kiinnityksen', '2022-04-01', 80.00),
(6, 'Mira', 'Tarkasti kaapelit', '2022-05-15', 60.00),
(7, 'Tommi', 'Puhdisti aurinkopaneelin', '2022-02-28', 90.00),
(8, 'Sami', 'Korjasi invertterin', '2022-03-20', 150.00),
(9, 'Timo', 'Vaihtoi paneelin', '2022-01-22', 180.00),
(10, 'Kari', 'Tarkasti kiinnityksen', '2021-12-05', 75.00);

INSERT INTO `mydb`.`Tarvikkeet` (`kaytetyt_tarvikkeet`, `tarvikkeiden_kokonaishinta`) VALUES
('Kiinnikkeet, johtimet, liittimet', 50.00),
('Lämpöliittimet, kaapelikourut', 65.00),
('Ruuvit, mutterit, prikat', 20.00),
('Tiivisteet, kaapelinippusiteet', 30.00),
('Kondensaattorit, diodit, vastukset', 80.00),
('Muuntajat, sulakkeet, releet', 110.00),
('Jännitteensäätimet, piirilevyt', 95.00),
('Kaapelit, sulakkeet, ohjainyksiköt', 125.00),
('Työkalut, mittalaitteet, suojauslaitteet', 150.00),
('Valaisimet, muut pienet tarvikkeet', 45.00);


INSERT INTO `mydb`.`Aurinkopaneeli_has_Asennus` (`Aurinkopaneeli_id`, `Asennus_id`, `Asennus_Asentaja_id`)
VALUES
(1, 1, 1),
(2, 2, 2),
(3, 3, 3),
(4, 4, 4),
(5, 5, 5),
(6, 6, 6),
(7, 7, 7),
(8, 8, 8),
(9, 9, 9),
(10, 10, 10);


INSERT INTO `mydb`.`Kokonaiskustannukset` (`kustannukset_yhteensa`, `Aurinkopaneeli_id`, `Asennus_id`, `Asennus_Asentaja_id`, `Tarvikkeet_id`) 
VALUES 
  (2000.00, 1, 1, 1, 1),
  (3500.00, 2, 2, 2, 2),
  (2400.00, 3, 3, 3, 3),
  (2750.00, 4, 4, 4, 4),
  (3100.00, 5, 5, 5, 5),
  (1950.00, 6, 6, 6, 6),
  (4000.00, 7, 7, 7, 7),
  (3650.00, 8, 8, 8, 8),
  (2800.00, 9, 9, 9, 9),
  (4200.00, 10, 10, 10, 10);

-- -----------------------------------------------------
-- hakulauseiden lisäys tauluille ja näkymille
-- -----------------------------------------------------
SELECT * FROM `Kayttaja`;

SELECT * FROM `Aurinkopaneeli`;

SELECT * FROM `Asentaja`;

SELECT * FROM `Asennus`;

SELECT * FROM `Tarvikkeet`;

SELECT * FROM `Huolto`;

SELECT * FROM `Kokonaiskustannukset`;

SELECT * FROM aurinkopaneeli_asennus_view;

SELECT paikkakunta, avg_hinta FROM paikkakunta_hinta_view;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
